baseURL = "https://myblog-alpha-mauve.vercel.app/"
languageCode = 'zh-cn'
title = 'caulif的个人博客'
theme = 'PaperMod'

[outputs]
  home = ["HTML", "JSON"]

[params]
  defaultTheme = "auto"
  description = "caulif的个人博客"
  keywords = ["博客", "技术", "生活"]

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/你的用户名"
