baseURL = "https://myblog-alpha-mauve.vercel.app/"
languageCode = 'zh-cn'
title = 'caulif的个人博客'
theme = 'PaperMod'

[outputs]
  home = ["HTML", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[params]
  defaultTheme = "auto"
  description = "caulif的个人博客"
  keywords = ["博客", "技术", "生活"]
  math = true

[params.analytics.google]
  ID = "G-1XVSZMDCP6"

[params.assets]
  disableFingerprinting = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/caulif"
