baseURL = "https://myblog-alpha-mauve.vercel.app/"
languageCode = 'zh-cn'
title = 'caulifçš„ä¸ªäººåšå®¢'
theme = 'PaperMod'
[services]
    [services.googleAnalytics]
        id = "G-1XVSZMDCP6"

[outputs]
  home = ["HTML", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[params]
  env = "production"
  defaultTheme = "auto"
  description = "caulifçš„ä¸ªäººåšå®¢"
  keywords = ["åšå®¢", "æŠ€æœ¯", "ç”Ÿæ´»"]
  math = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowWordCount = true

[params.homeInfoParams]
  Title = "ğŸ‘‹ æ¬¢è¿æ¥åˆ° caulif çš„åšå®¢"
  Content = "è®°å½•æŠ€æœ¯å­¦ä¹ ä¸æ€è€ƒ"

[params.profileMode]
  enabled = false

[params.assets]
  disableFingerprinting = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/caulif"

