baseURL = "https://myblog-alpha-mauve.vercel.app/"
languageCode = 'zh-cn'
title = 'caulif的个人博客'
theme = 'PaperMod'
[services]
    [services.googleAnalytics]
        id = "G-1XVSZMDCP6"

[outputs]
  home = ["HTML", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[params]
  env = "production"
  defaultTheme = "auto"
  description = "caulif的个人博客"
  keywords = ["博客", "技术", "生活"]
  math = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true

[params.profileMode]
  enabled = false

[params.assets]
  disableFingerprinting = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/caulif"

